services:
  odoo-db:
    image: postgres:16
    container_name: odoo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 10

  odoo:
    image: odoo:19.0
    container_name: odoo
    restart: unless-stopped
    depends_on:
      odoo-db:
        condition: service_healthy
    ports:
      - "8069:8069"
    environment:
      HOST: odoo-db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    command:
      - odoo
      - --http-interface=0.0.0.0
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-extra-addons:/mnt/extra-addons

volumes:
  odoo-db-data:
  odoo-web-data:
  odoo-extra-addons:
